# Generated by Django 2.0.6 on 2018-06-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_text', models.CharField(max_length=100000)),
                ('horario_text', models.CharField(max_length=100000)),
                ('username', models.CharField(max_length=100000)),
            ],
        ),
    ]
