# Generated by Django 2.0.6 on 2018-06-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='horario_text',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='score_text',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
