# Generated by Django 2.0.6 on 2018-06-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20180628_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='horario_text',
            field=models.CharField(default=' ', max_length=100000),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='score_text',
            field=models.CharField(default=' ', max_length=100000),
        ),
    ]
