# Generated by Django 2.0.6 on 2018-06-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('integrales', models.IntegerField(default=0)),
                ('derivadas', models.IntegerField(default=0)),
                ('matrices', models.IntegerField(default=0)),
            ],
        ),
    ]
