# Generated by Django 2.0.6 on 2018-06-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identificacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSheet',
        ),
    ]
