# Generated by Django 2.0.6 on 2018-06-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
