# Generated by Django 2.0.6 on 2018-06-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identificacion', '0002_auto_20180615_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='derivadas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasheet',
            name='integrales',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasheet',
            name='matrices',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
