# Generated by Django 2.0.6 on 2018-06-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identificacion', '0003_auto_20180615_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='derivadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='integrales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='matrices',
            field=models.IntegerField(default=0),
        ),
    ]
